name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    # Build Core and Console using CMake
    - name: Configure CMake (Core and Console)
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBUILD_CONSOLE=ON -DBUILD_WINUI=OFF
      
    - name: Build Core and Console
      run: cmake --build build --config ${{ matrix.config }}
    
    # Build WinUI using MSBuild
    - name: Restore NuGet packages for WinUI
      working-directory: src/winui
      run: nuget restore packages.config -PackagesDirectory packages
    
    - name: Debug - List WinUI directory
      run: dir src\winui
      
    - name: Build WinUI Application  
      run: msbuild ${{ github.workspace }}/src/winui/Mouse2VR_WinUI.vcxproj /p:Configuration=${{ matrix.config }} /p:Platform=x64 /p:OutDir=${{ github.workspace }}\build\bin\${{ matrix.config }}\ /p:IntDir=${{ github.workspace }}\build\obj\winui\
    
    - name: Copy WinUI dependencies
      if: matrix.config == 'Release'
      run: |
        $outputDir = "${{ github.workspace }}\build\bin\${{ matrix.config }}"
        
        # Copy Windows App SDK runtime
        Copy-Item "src\winui\packages\Microsoft.WindowsAppSDK.*\runtimes\win-x64\native\*.dll" -Destination $outputDir -Force -ErrorAction SilentlyContinue
        
        # Copy ViGEmClient DLL
        if (Test-Path "build\bin\${{ matrix.config }}\ViGEmClient.dll") {
          Copy-Item "build\bin\${{ matrix.config }}\ViGEmClient.dll" -Destination $outputDir -Force
        }
      
    - name: Upload Artifacts
      if: matrix.config == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: Mouse2VR-${{ matrix.config }}
        path: |
          build/bin/${{ matrix.config }}/Mouse2VR.exe
          build/bin/${{ matrix.config }}/Mouse2VR_WinUI.exe
          build/bin/${{ matrix.config }}/*.dll
          build/bin/${{ matrix.config }}/resources.pri