name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    # Build Core, Console and WebView2 using CMake
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DBUILD_CONSOLE=ON -DBUILD_WEBVIEW=ON -DBUILD_WINUI=OFF
      
    - name: Build All Targets
      run: cmake --build build --config ${{ matrix.config }}
    
    # Copy dependencies
    - name: Copy dependencies
      if: matrix.config == 'Release'
      run: |
        $outputDir = "${{ github.workspace }}\build\bin\${{ matrix.config }}"
        
        # Copy ViGEmClient DLL
        if (Test-Path "build\bin\${{ matrix.config }}\ViGEmClient.dll") {
          Copy-Item "build\bin\${{ matrix.config }}\ViGEmClient.dll" -Destination $outputDir -Force
        }
      
    - name: Upload Artifacts
      if: matrix.config == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: Mouse2VR-${{ matrix.config }}
        path: |
          build/bin/${{ matrix.config }}/Mouse2VR.exe
          build/bin/${{ matrix.config }}/Mouse2VR_WinUI.exe
          build/bin/${{ matrix.config }}/*.dll
          build/bin/${{ matrix.config }}/resources.pri